// import React from "react";
// import type { Metadata } from "next";
// import { ClerkProvider } from "@clerk/nextjs";

// import { Inter } from "next/font/google";
// import "./globals.css";
// import { ProductProvider } from "./context/ProductContext";
// import Navbar from "./components/Home/Navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Avion",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={inter.className}>
//           <ProductProvider>
//             <Navbar />
//             {children}
//           </ProductProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }


import React, { Suspense } from "react";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

import "./globals.css";
import { ProductProvider } from "./context/ProductContext";
import Navbar from "./components/Home/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Avion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ProductProvider>
            <Navbar />
            {/* Suspense is needed to handle async ClerkProvider */}
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
          </ProductProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
