import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "./context/ProductContext";
import Navbar from "./components/Home/Navbar";
import DynamicClerkProvider from "./components/Home/DynamicClerkProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Avion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DynamicClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ProductProvider>
            <Navbar />
            {children}
          </ProductProvider>
        </body>
      </html>
    </DynamicClerkProvider>
  );
}
